### PR TITLE
Add optional -c flag to output curl command for successful requests

### PR DESCRIPTION
**Pull request by tomquinn8**
The first thing I wanted to do when I got a "200" response was to see the actual response so I've added an optional -c flag to echo the appropriate curl command for requests which have returned a 2xx status code.

### CODE REVIEW

**Review by lobuhi — CHANGES_REQUESTED** [review]
Nice contribution!

I would add your "if" statement inside the "if status =~ 2.." because your're doing two curl request and saving its value everytime, even if the returned status is not 200, so we lose performance.

So, may you move your "if" statement two lines below just right after "then" and before the 200 "echo", please? Don't u think it would be better?

Thx!

**Comment by tomquinn8** [comment]
I did consider that when I wrote it but yes you're right it makes more sense there.

Changes made and README updated to include -c flag.

Thank you!

**Comment by lobuhi** [comment]
Some curls need additional parameters:
- HEAD needs -m timeout option
- /. and /./ needs --path-as-is

Let me check it later and I'll merge it ;)

**Comment by tomquinn8** [comment]
Sorry my fault, should be fixed now.

Thank you!

**Pull request merged**
